### DISCUSSION TITLE
New qss for Zeal

### DISCUSSION THREAD

**Discussion by cathaysia** [zealdocs/zeal#1311] [Show and tell]
Hi, I write a qss for Zeal, It works on my computer. I hope it could be avaible for everyone, should we consider it?

Beacuse I don't want change the code, and import asstes, so some widget not changed.
[style.zip](https://github.com/zealdocs/zeal/files/5824055/style.zip)

![mainwindow](https://user-images.githubusercontent.com/42114817/104806710-7c201680-5814-11eb-95a6-f8dafe3163c5.png)
![docsets_dialog](https://user-images.githubusercontent.com/42114817/104806716-83472480-5814-11eb-8e53-9545bfdebbfc.png)
![perferences](https://user-images.githubusercontent.com/42114817/104806718-86421500-5814-11eb-9f6e-6b554e3ca261.png)

The qss content is :

```css
* {
    font-family: "Microsoft YaHei";
    font-size: 16px;
}
QPushButton{
    background: #FFF;
    border: 1px solid #DCDFE6;
    color: #606266;
    padding: 7px 10px;
    min-height: 15px;
    border-radius: 5px;
}

QPushButton:hover{
    color: #409EFF;
    border-color: #c6e2ff;
    background-color: #ecf5ff;
}

QPushButton:pressed{
    color: #3a8ee6;
    border-color: #3a8ee6;
    outline: 0;
}
QPushButton:disabled{
    background-color: #FFFFFF;
    color: #c0c4cc;
}

QLineEdit{
    color: #606266;
    border: 1px solid #dcdfe6;
    border-radius: 4px;
    padding: 7px;
}
QLineEdit:disabled{
    color: #c0c4cc;
    /* background-color: #F5F7FA; */
    border-color: #e4e7ed;
}
QTabWidget::pane{
    background-color: white;
    border: 1px solid transparent;
}
QTabBar::tab{
    background-color: #F5F7FA;
    color: #909399;
    border: 1px solid transparent;
    padding: 7px 20px;
    font-weight: 400;
}
QTabBar::tab:selected{
    background-color: white;
    color: #409eff;
}

/* QScrollBar:vertical {
    background-color: #fff;
}
QScrollBar::handle:vertical {
    min-width: 16px;
    background-color: #A0CFFF;
    border-radius: 8px;
}
QScrollBar::handle:vertical:hover{
    background-color: #409EFF;
} */


QListView {
    color: black;
    background-color: #fff;
    outline:0px;
    show-decoration-selected: 1;
}
QListView::item{
    color: #606266;
    padding: 4px 0;
    border-bottom: 1px solid #ebeef5;
}
QListView::item:selected {
    background-color: #F0F0F0;
}
QListView::item:hover {
    background-color: #F5F7FA;
}
QMenuBar{
    background-color: white;
    color: black;
    padding: 8px 10px;
    border: none;
    /* border-bottom: 1px solid gray; */
}
QMenuBar::item{
    background-color: #fff;
}
QMenuBar::item:selected{
    color: #409EFF;
}
QMenu{
    background-color: white;
    color: black;
    /* font-weight: 400; */
    border: 1px dotted  #001529;
    padding: 2px;
}
QMenu::item{
    font-size: 16px;
    padding: 8px;
}
QMenu::item:selected{
    background-color: #E6F7FF;
    color: #409EFF;
    /* background-color: #; */
}
```

QScrollBarBar will make bug for docset_dialog, so I comment it.

Thanks element https://element.eleme.cn/ and antd https://ant.design
