### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by trollixx** [zealdocs/zeal#466]
Provide a dark mode similarly to Dash.

Related to #268

**Comment by vgturtle127** [comment]
:+1:

**Comment by rgulle4** [comment]
:+1:

**Comment by pawelkuras** [comment]
:+1:

**Comment by anephew** [comment]
:+1:

**Comment by Dieterbe** [comment]
Yes please !

**Comment by jcherqui** [comment]
:+1:

**Comment by trollixx** [comment]
@Kapeli How's Dash implementing this? Is there a class I should add, or everything is overridden by an external CSS? Thanks!

**Comment by Kapeli** [comment]
This is the CSS Dash uses for dark mode:

```css
iframe {
    -webkit-filter: invert()
}
html {
    -webkit-filter: invert() contrast(80%) brightness(120%) contrast(85%);
}
html img[src*=\"jpg\"], html img[src*=\"jpeg\"], html img[src*=\"jpg\"], html img[src*=\"jpeg\"] { 
    -webkit-filter: brightness(100%) contrast(100%); 
}
```

Adding a `hue-rotate` makes it a lot nicer as it preserves the colors, but it causes performance issues on OS X so I don't use it.
```css
html { 
    -webkit-filter: invert() hue-rotate(180deg) contrast(80%) brightness(120%) contrast(85%); 
}
```
